### ISSUE TITLE
EPR Import Not Working

### ISSUE THREAD

**Issue by sloping0083** [AF-VCD/pdf-bullets#85] opened 2022-12-27 09:22 UTC
Not sure if it's just me. I tried Chrome and Edge on AFNET machine. Trying to import a 910, dated 20220316 and it's not working.

**Comment by ckhordiasma** [comment] 2022-12-27 15:28
Can you upload a blank/test version of the form that is not working? Thanks

**Comment by sloping0083** [comment] 2022-12-28 07:16
It's the regular 910 off of e-pubs. Here it is and thank you for looking into it.
[daf910.pdf](https://github.com/AF-VCD/pdf-bullets/files/10312755/daf910.pdf)

**Comment by sloping0083** [comment] 2023-01-05 19:16
any update by any chance?

**Comment by ckhordiasma** [comment] 2023-01-08 18:30
sorry for the delay, fixed in https://github.com/AF-VCD/pdf-bullets/pull/86 . might take a day to propagate to the actual website(s). 

issue was caused by the fact that the form names in the form metadata were changed from AF to DAF, i.e. AF910 to DAF910

**Closed by ckhordiasma** 2023-01-08 18:30 UTC
